apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photoprism-chart.fullname" . }}
  labels:
    {{- include "photoprism-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  strategy:
    type: Recreate      
  selector:
    matchLabels:
      {{- include "photoprism-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "photoprism-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "photoprism-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: photoprism-storage
              mountPath: /photoprism/storage
            - name: photoprism-import
              mountPath: /photoprism/originals
          ports:
            - name: http
              containerPort: 2342
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range $key, $val := .Values.environmentvars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}      
        - name: resilio-sidecar
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: resilio/sync:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: resilio-data
              mountPath: /mnt/sync
            - name: photoprism-import
              mountPath: /mnt/mounted_folders/photoprism-import
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range $key, $val := .Values.environmentvars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: photoprism-storage
          persistentVolumeClaim:
            claimName: photoprism-storage
        - name: photoprism-import
          persistentVolumeClaim:
            claimName: photoprism-import
        - name: resilio-data
          persistentVolumeClaim:
            claimName: resilio-data
  